os: osx
osx_image: xcode10.2
language: swift
script: xcodebuild clean build -workspace ProductBrowser.xcworkspace -scheme "ProductBrowser" -sdk iphonesimulator -destination "platform=iOS Simulator,OS=12.4,name=iPhone 8" ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO